# Generated by Django 5.1.7 on 2025-03-21 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_service_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='title',
        ),
    ]
