# Generated by Django 5.1.7 on 2025-03-23 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_service_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='vehicle/')),
                ('title', models.TextField(max_length=20)),
                ('des', models.TextField(max_length=100)),
            ],
        ),
    ]
