# Generated by Django 5.1.7 on 2025-03-24 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_vehicle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Service',
            new_name='Clientlogo',
        ),
    ]
